### PR TITLE
Feat: Guild Member Counts Closes #112

### LINKED ISSUE #112: [FEATURE]
**Is your feature request related to a problem? Please describe.**
Fetching guild member counts is a separate URL.

**Describe the solution you'd like**
Thinking maybe a separate method, or adding member counts to the current fetch guilds method in DiscordService.

**Additional context**
I added member counts to the current fetch guilds method to fit my personal needs in my project, I would like to contribute this method, or create a second method that includes the guild member counts to fit other's needs that may want this feature.

### PR DESCRIPTION
**Pull request by DamoFD**
## Description
Added functionality to fetch Guild's approximate member counts, and approximate member presence.

## Related Issue
Closes #112 

## Changes Made

- Added approximate member counts, and approximate presence in the Guild Type.
- Added a method in DiscordService to fetch guilds with member counts.
- Added getGuildsWithMemberCounts method to InteractsWithDiscord.
- Adjusted Interacts_with_discord.mdx documentation to explain the new getGuildsWithMemberCounts method.

## Checklist
- [x] I have tested the changes locally and they are working as expected.
- [x] I have added appropriate documentation or updated existing documentation (if applicable).
- [x] I have ensured that my code follows the project's coding guidelines.
- [x] I have added necessary tests to cover the changes (if applicable).
- [x] I have rebased my branch onto the latest master/main branch.
- [x] I have resolved any merge conflicts that may arise.
- [x] I have reviewed and proofread my code for any errors or typos.

### CODE REVIEW

**Comment by JakyeRU** [comment]
Hello!

Looks good to me. But what about instead of creating another method (`getGuildsWithMemberCounts`) we leave this option as a parameter for the `getGuilds` method?

For example:
```php
auth()->user()->getGuilds(true)
```

Or maybe scratch this idea altogether and add the member count by default, since an additional request to Discord isn't needed for this.

What are your thoughts?

**Comment by DamoFD** [comment]
imo, probably the:

`getGuilds(true)`

I'm not sure why discord needs an additional parameter for the counts, but I'm sure there's a reason why you can fetch with and without the counts. For best user experience, I think both options should be available without having to edit any vendor files.

Let me know what you think, and I'll work on the edits 👍

**Comment by JakyeRU** [comment]
I agree with you. Both options should be available.

Once you make the necessary edits I'll merge this PR. :)

**Comment by DamoFD** [comment]
There we go, let me know what you think 👍

**Comment by JakyeRU** [comment]
Looks good to me.

Only one small change in the documentation.

Can you make the parameters similar to the `joinGuild` method?

https://larascord-git-fork-damofd-feat-member-counts-jakyeru.vercel.app/interacts_with_discord#parameters

**Comment by JakyeRU** [comment]
Everything seems to be good.

Thank you for your contribution! :)

**Pull request merged**
